services:
  back:
    build: ./back
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./back:/app
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
      - ./pihole/etc-pihole/hosts:/etc/pihole/hosts
      - ./ssl:/etc/ssl
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: always
    network_mode: "host"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./front/bssminfo/out:/usr/share/nginx/html/front:ro
      - ./nginx/data:/etc/nginx/data:ro
      - ./nginx/ssl:/etc/ssl:ro
    depends_on:
      - back

  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql  

  backup:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - ./backup:/backup
      - ./backup/scripts:/scripts
    env_file:
      - .env
    entrypoint: ["/scripts/backup.sh"]
    depends_on:
      - db

  kea:
    build: 
      context: ./kea
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./kea/config:/etc/kea
      - ./kea/logs:/var/log/kea
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BROADCAST
    restart: unless-stopped
    depends_on:
      - db

  tftp:
    image: 3x3cut0r/tftpd-hpa
    network_mode: "host"
    environment:
      TZ: Asia/Seoul
      CREATE: 1
      VERBOSE: 1
      VERBOSITY: 4
      SECURE: 1
      PERMISSIVE: 1
      MAXPROC: 4
      MAPFILE: ""   
    volumes:
      - ./tftp/data:/tftpboot
    restart: unless-stopped

  smb:
    image: dperson/samba
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - ./smb/initsetup:/setup
      - ./smb/setup:/oldsetup
      - ./smb/bssmdata:/bssmdata
    env_file:
      - .env
    environment:
      USERID: 1000
      GROUPID: 1000
      TZ: Asia/Seoul
      WORKGROUP: "WORKGROUP"
    restart: unless-stopped
    command: >
      -p
      -S
      -g "security = user"
      -g "map to guest = Bad User"
      -g "server min protocol = SMB2"
      -g "server max protocol = SMB3"
      -g "client min protocol = SMB2"
      -g "client max protocol = SMB3"
      -g "ntlm auth = yes"
      -g "unix charset = UTF-8"
      -g "dos charset = CP932"
      -g "max connections = 1000"
      -g "deadtime = 30"
      -g "keepalive = 60"
      -g "log level = 3"
      -g "multiuser = yes"
      -g "max protocol = SMB3"
      -g "server multi channel support = yes"
      -g "directory mask = 0777"
      -g "create mask = 0777"
      -u "${SAMBA_USER};${SAMBA_PASSWORD}"
      -s "setup;/setup;yes;yes;no;${SAMBA_USER}"
      -s "oldsetup;/oldsetup;yes;yes;no;${SAMBA_USER}"
      -s "BSSMShare;/bssmdata;yes;no;no;${SAMBA_USER}"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  # dns:
  #   image: mvance/unbound:latest
  #   ports:
  #     - "1053:53/udp"
  #     - "1053:53/tcp"
  #   volumes:
  #     - ./dns:/opt/unbound/etc/unbound
  #   restart: unless-stopped

  dns2:
    image: pihole/pihole:latest
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "127.0.0.1:8888:80/tcp"
    environment:
      TZ: 'Asia/Seoul'
      DNSMASQ_USER: pihole
      VIRTUAL_HOST: pihole.local
      PROXY_LOCATION: pihole
      ServerIP: 10.129.55.253
      DNSMASQ_LISTENING: all
      PIHOLE_DNSMASQ_USER: pihole
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
      - ./pihole/watch_custom_list.sh:/etc/pihole/watch_custom_list.sh
    restart: unless-stopped
    shm_size: 512mb
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "
        chmod +x /etc/pihole/watch_custom_list.sh &&
        nohup /etc/pihole/watch_custom_list.sh > /dev/null 2>&1 &
        /start.sh
      "

  
