# Generated by Django 5.1.6 on 2025-06-28 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_id', models.CharField(max_length=100, unique=True, verbose_name='프리뷰 ID')),
                ('broadcast_type', models.CharField(choices=[('text', '텍스트 방송'), ('audio', '음성 방송')], max_length=10, verbose_name='방송 타입')),
                ('content', models.TextField(verbose_name='방송 내용')),
                ('target_rooms', models.JSONField(default=list, verbose_name='대상 방 목록')),
                ('language', models.CharField(default='ko', max_length=5, verbose_name='언어')),
                ('auto_off', models.BooleanField(default=False, verbose_name='자동 끄기')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('ready', '준비됨'), ('approved', '승인됨'), ('rejected', '거부됨'), ('expired', '만료됨')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('expires_at', models.DateTimeField(verbose_name='만료일')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='거부 사유')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_previews', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='broadcast.audiofile', verbose_name='프리뷰 오디오 파일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '방송 프리뷰',
                'verbose_name_plural': '방송 프리뷰',
                'db_table': 'broadcast_preview',
                'ordering': ['-created_at'],
            },
        ),
    ]
