# Generated by Django 5.1.6 on 2025-06-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_broadcastpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcasthistory',
            name='external_response',
            field=models.JSONField(blank=True, null=True, verbose_name='외부 API 응답'),
        ),
    ]
