# Generated by Django 5.1.6 on 2025-06-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_broadcasthistory_external_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcasthistory',
            name='audio_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='broadcast.audiofile', verbose_name='방송 오디오 파일'),
        ),
    ]
