# Generated by Django 5.1.6 on 2025-06-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0004_broadcasthistory_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcasthistory',
            name='preview_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='프리뷰 ID'),
        ),
    ]
