# Generated by Django 5.1.6 on 2025-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0002_customdnsrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdnsrequest',
            name='status',
            field=models.CharField(choices=[('대기', '대기'), ('승인', '승인'), ('거절', '거절'), ('삭제됨', '삭제됨')], default='대기', max_length=10),
        ),
    ]
