# Generated by Django 5.1.6 on 2025-06-26 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0003_alter_customdnsrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='CA 이름')),
                ('certificate', models.TextField(verbose_name='CA 인증서 (PEM 형식)')),
                ('private_key', models.TextField(verbose_name='CA 개인키 (PEM 형식)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '인증 기관',
                'verbose_name_plural': '인증 기관 목록',
                'db_table': 'certificate_authorities',
            },
        ),
        migrations.AddField(
            model_name='customdnsrecord',
            name='ssl_enabled',
            field=models.BooleanField(default=False, verbose_name='SSL 활성화'),
        ),
        migrations.AddField(
            model_name='customdnsrequest',
            name='ssl_enabled',
            field=models.BooleanField(default=False, verbose_name='SSL 인증서 발급'),
        ),
        migrations.CreateModel(
            name='SslCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('certificate', models.TextField(verbose_name='인증서 (PEM 형식)')),
                ('private_key', models.TextField(verbose_name='개인키 (PEM 형식)')),
                ('certificate_chain', models.TextField(blank=True, null=True, verbose_name='인증서 체인')),
                ('status', models.CharField(choices=[('발급중', '발급중'), ('활성', '활성'), ('만료', '만료'), ('오류', '오류')], default='발급중', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('dns_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certificate', to='dns.customdnsrecord')),
            ],
            options={
                'verbose_name': 'SSL 인증서',
                'verbose_name_plural': 'SSL 인증서 목록',
                'db_table': 'ssl_certificates',
            },
        ),
    ]
