# Generated by Django 5.1.6 on 2025-06-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0004_certificateauthority_customdnsrecord_ssl_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdnsrequest',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '거절'), ('deleted', '삭제됨')], default='대기', max_length=10),
        ),
    ]
