# Generated by Django 5.1.6 on 2025-06-29 08:03

from django.db import migrations


def convert_status_to_english(apps, schema_editor):
    """기존 한글 상태를 영어로 변환"""
    CustomDnsRequest = apps.get_model('dns', 'CustomDnsRequest')
    
    # 한글 상태를 영어로 변환
    status_mapping = {
        '대기': 'pending',
        '승인': 'approved',
        '거절': 'rejected',
        '삭제됨': 'deleted'
    }
    
    for request in CustomDnsRequest.objects.all():
        if request.status in status_mapping:
            request.status = status_mapping[request.status]
            request.save()


def convert_status_to_korean(apps, schema_editor):
    """영어 상태를 한글로 되돌리기 (롤백용)"""
    CustomDnsRequest = apps.get_model('dns', 'CustomDnsRequest')
    
    # 영어 상태를 한글로 변환
    status_mapping = {
        'pending': '대기',
        'approved': '승인',
        'rejected': '거절',
        'deleted': '삭제됨'
    }
    
    for request in CustomDnsRequest.objects.all():
        if request.status in status_mapping:
            request.status = status_mapping[request.status]
            request.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0005_update_status_to_english'),
    ]

    operations = [
        migrations.RunPython(convert_status_to_english, convert_status_to_korean),
    ]
