# Generated by Django 5.1.6 on 2025-06-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0007_convert_dns_status_to_english'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sslcertificate',
            name='private_key',
        ),
    ]
