# Generated by Django 5.1.6 on 2025-07-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0008_remove_private_key_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslcertificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='폐기일'),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='serial_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='인증서 시리얼 번호'),
        ),
        migrations.AlterField(
            model_name='sslcertificate',
            name='status',
            field=models.CharField(choices=[('발급중', '발급중'), ('활성', '활성'), ('만료', '만료'), ('오류', '오류'), ('폐기', '폐기')], default='발급중', max_length=10),
        ),
    ]
