# Generated by Django 5.1.6 on 2025-03-02 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceLease',
        ),
    ]
