# Generated by Django 5.1.6 on 2025-06-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_delete_devicelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehistory',
            name='new_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicehistory',
            name='old_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='action',
            field=models.CharField(choices=[('REGISTER', 'Register'), ('UNREGISTER', 'Unregister'), ('REASSIGN_IP_BLACKLIST', 'Reassign Ip Blacklist')], max_length=30),
        ),
    ]
