# Generated by Django 5.1.6 on 2025-06-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_devicehistory_new_value_devicehistory_old_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '블랙리스트 IP',
                'verbose_name_plural': '블랙리스트 IP 목록',
                'db_table': 'blacklisted_ips',
            },
        ),
    ]
