# Generated by Django 5.1.6 on 2025-06-25 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_blacklistedip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDnsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '커스텀 DNS 레코드',
                'verbose_name_plural': '커스텀 DNS 레코드 목록',
                'db_table': 'custom_dns_records',
            },
        ),
        migrations.CreateModel(
            name='CustomDnsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('대기', '대기'), ('승인', '승인'), ('거절', '거절')], default='대기', max_length=10)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '커스텀 DNS 요청',
                'verbose_name_plural': '커스텀 DNS 요청 목록',
                'db_table': 'custom_dns_requests',
            },
        ),
    ]
