# Generated by Django 5.1.6 on 2025-06-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_customdnsrecord_customdnsrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomDnsRecord',
        ),
        migrations.DeleteModel(
            name='CustomDnsRequest',
        ),
    ]
