# Generated by Django 5.1.6 on 2025-03-01 18:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='장비명')),
                ('equipment_type', models.CharField(choices=[('LAPTOP', '노트북'), ('TABLET', '태블릿'), ('PROJECTOR', '프로젝터'), ('OTHER', '기타')], max_length=20, verbose_name='장비 종류')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='일련번호')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('AVAILABLE', '대여 가능'), ('RENTED', '대여 중'), ('MAINTENANCE', '점검 중'), ('LOST', '분실'), ('DAMAGED', '손상')], default='AVAILABLE', max_length=20, verbose_name='상태')),
                ('acquisition_date', models.DateField(verbose_name='취득일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '장비',
                'verbose_name_plural': '장비들',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='대여일')),
                ('due_date', models.DateTimeField(verbose_name='반납 예정일')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='실제 반납일')),
                ('status', models.CharField(choices=[('RENTED', '대여 중'), ('RETURNED', '반납 완료'), ('OVERDUE', '연체'), ('LOST', '분실'), ('DAMAGED', '손상')], default='RENTED', max_length=20, verbose_name='상태')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rentals', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rentals.equipment', verbose_name='장비')),
                ('returned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returns', to=settings.AUTH_USER_MODEL, verbose_name='반납 확인자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '대여',
                'verbose_name_plural': '대여 내역',
            },
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('RENT', '대여 신청'), ('RETURN', '반납 신청')], max_length=10, verbose_name='요청 유형')),
                ('status', models.CharField(choices=[('PENDING', '승인 대기'), ('APPROVED', '승인됨'), ('REJECTED', '거부됨'), ('CANCELLED', '취소됨')], default='PENDING', max_length=10, verbose_name='상태')),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='신청일')),
                ('expected_return_date', models.DateTimeField(blank=True, null=True, verbose_name='반납 예정일')),
                ('reason', models.TextField(blank=True, verbose_name='사유')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='rentals.equipment', verbose_name='장비')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='rentals.rental', verbose_name='대여 정보')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '대여/반납 요청',
                'verbose_name_plural': '대여/반납 요청들',
            },
        ),
    ]
