# Generated by Django 5.1.6 on 2025-03-03 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_delete_devicelease'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='returned_to',
        ),
        migrations.AddField(
            model_name='equipment',
            name='item_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='물품번호'),
        ),
        migrations.AddField(
            model_name='rental',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_rentals', to='devices.device', verbose_name='연결된 장치'),
        ),
        migrations.AddField(
            model_name='rental',
            name='handover_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_rentals', to=settings.AUTH_USER_MODEL, verbose_name='인계자'),
        ),
        migrations.AddField(
            model_name='rental',
            name='receiver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_rentals', to=settings.AUTH_USER_MODEL, verbose_name='인수자'),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_handover_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_handover_rentals', to=settings.AUTH_USER_MODEL, verbose_name='반납 인계자'),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_receiver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_receiver_rentals', to=settings.AUTH_USER_MODEL, verbose_name='반납 인수자'),
        ),
    ]
