# Generated by Django 5.1.6 on 2025-04-10 03:20

import django.db.models.deletion
import rentals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_remove_rental_approved_by_remove_rental_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='item_number',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='device',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='handover_user',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='receiver_user',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='return_handover_user',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='return_receiver_user',
        ),
        migrations.AddField(
            model_name='rental',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rentals', to=settings.AUTH_USER_MODEL, verbose_name='승인자'),
        ),
        migrations.AddField(
            model_name='rental',
            name='due_date',
            field=models.DateTimeField(default=rentals.models.get_default_due_date, verbose_name='반납 예정일'),
        ),
        migrations.AddField(
            model_name='rental',
            name='returned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returns', to=settings.AUTH_USER_MODEL, verbose_name='반납 확인자'),
        ),
    ]
