# Generated by Django 5.1.6 on 2025-04-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_equipment_options_equipment_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('LAPTOP', '노트북'), ('TABLET', '태블릿'), ('DESKTOP', '데스크톱'), ('MONITOR', '모니터'), ('KEYBOARD', '키보드'), ('MOUSE', '마우스'), ('PRINTER', '프린터'), ('PROJECTOR', '프로젝터'), ('OTHER', '기타')], max_length=20, verbose_name='장비 유형'),
        ),
    ]
