# Generated by Django 5.1.6 on 2025-04-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_remove_rentalrequest_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='manufacture_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='제작년도'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='구입일시'),
        ),
    ]
