# Generated by Django 5.1.6 on 2025-06-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_equipment_manufacture_year_equipment_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='asset_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='물품번호'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='management_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='관리번호'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='구입금액'),
        ),
    ]
