# Generated by Django 5.1.6 on 2025-06-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_remove_equipment_name_equipment_asset_number_and_more'),
        ('rentals', 'update_management_numbers'),
    ]

    operations = [
    ]
