# Generated by Django 5.1.6 on 2025-06-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_alter_equipment_equipment_type'),
    ]

    operations = [
    ]
