# Generated by Django 5.1.6 on 2025-06-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_reassign_management_numbers'),
    ]

    operations = [
    ]
