# Generated by Django 5.1.6 on 2025-06-18 00:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_alter_equipment_equipment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalrequest',
            options={'ordering': ['-requested_date'], 'verbose_name': '대여 요청', 'verbose_name_plural': '대여 요청들'},
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='expected_return_date',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='request_reason',
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='processed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='처리일'),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='request_type',
            field=models.CharField(choices=[('RENTAL', '대여 요청'), ('RETURN', '반납 요청')], max_length=20, verbose_name='요청 유형'),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='requested_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='요청일'),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기 중'), ('APPROVED', '승인됨'), ('REJECTED', '거부됨'), ('CANCELLED', '취소됨')], default='PENDING', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', '생성'), ('UPDATED', '수정'), ('STATUS_CHANGED', '상태 변경'), ('RENTED', '대여'), ('RETURNED', '반납'), ('DELETED', '삭제')], max_length=20, verbose_name='작업')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='이전 값')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='새 값')),
                ('details', models.TextField(blank=True, verbose_name='상세 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작업일시')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='rentals.equipment', verbose_name='장비')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작업자')),
            ],
            options={
                'verbose_name': '장비 이력',
                'verbose_name_plural': '장비 이력들',
                'ordering': ['-created_at'],
            },
        ),
    ]
