# Generated by Django 5.1.6 on 2025-06-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0016_alter_rentalrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='expected_return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='반납 예정일'),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='거부 사유'),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='request_reason',
            field=models.TextField(blank=True, verbose_name='요청 사유'),
        ),
    ]
