# Generated by Django 5.1.6 on 2025-07-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_new_management_number_system'),
        ('rentals', '0017_rentalrequest_expected_return_date_and_more'),
    ]

    operations = [
    ]
