# Generated by Django 5.1.6 on 2025-07-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0018_merge_20250731_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='management_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='관리번호'),
        ),
    ]
