# Generated by Django 5.1.6 on 2025-08-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0019_alter_management_number_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='구입일'),
        ),
    ]
