# Generated by Django 5.1.6 on 2025-08-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0020_alter_equipment_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='취득일'),
        ),
    ]
