# Generated by Django 5.1.6 on 2025-06-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_class_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_limit',
            field=models.IntegerField(default=3, help_text='최대 등록 가능한 장치 수'),
        ),
    ]
