# Generated by Django 5.1.6 on 2025-06-30 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='정책 이름')),
                ('description', models.TextField(blank=True, verbose_name='정책 설명')),
                ('totp_interval', models.IntegerField(default=30, verbose_name='TOTP 간격 (초)')),
                ('totp_digits', models.IntegerField(default=6, verbose_name='TOTP 자릿수')),
                ('totp_window', models.IntegerField(default=1, verbose_name='TOTP 검증 윈도우')),
                ('default_key_length', models.IntegerField(default=64, verbose_name='기본 키 길이')),
                ('max_keys_per_user', models.IntegerField(default=5, verbose_name='사용자당 최대 키 수')),
                ('key_expiry_days', models.IntegerField(default=365, verbose_name='키 만료 일수')),
                ('default_rate_limit_per_minute', models.IntegerField(default=100, verbose_name='기본 분당 요청 제한')),
                ('default_rate_limit_per_hour', models.IntegerField(default=1000, verbose_name='기본 시간당 요청 제한')),
                ('require_totp_for_sensitive_operations', models.BooleanField(default=True, verbose_name='민감한 작업에 TOTP 요구')),
                ('log_all_requests', models.BooleanField(default=True, verbose_name='모든 요청 로깅')),
                ('block_suspicious_ips', models.BooleanField(default=True, verbose_name='의심스러운 IP 차단')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '보안 정책',
                'verbose_name_plural': '보안 정책들',
            },
        ),
        migrations.CreateModel(
            name='TOTPAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='API 키 이름')),
                ('totp_secret', models.CharField(max_length=255, verbose_name='TOTP 시크릿 키')),
                ('api_key_hash', models.CharField(max_length=255, verbose_name='API 키 해시')),
                ('salt', models.CharField(max_length=64, verbose_name='솔트')),
                ('permissions', models.JSONField(default=list, verbose_name='권한 목록')),
                ('max_requests_per_minute', models.IntegerField(default=100, verbose_name='분당 최대 요청 수')),
                ('max_requests_per_hour', models.IntegerField(default=1000, verbose_name='시간당 최대 요청 수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료 시간')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 사용 시간')),
                ('total_requests', models.IntegerField(default=0, verbose_name='총 요청 수')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='실패 시도 수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_api_keys', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'TOTP API 키',
                'verbose_name_plural': 'TOTP API 키들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255, verbose_name='엔드포인트')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP 메서드')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('status_code', models.IntegerField(verbose_name='응답 상태 코드')),
                ('response_time', models.FloatField(verbose_name='응답 시간 (초)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='요청 시간')),
                ('success', models.BooleanField(verbose_name='성공 여부')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api_security.totpapikey', verbose_name='API 키')),
            ],
            options={
                'verbose_name': 'API 키 사용 로그',
                'verbose_name_plural': 'API 키 사용 로그들',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['api_key', 'timestamp'], name='api_securit_api_key_56d67f_idx'), models.Index(fields=['ip_address', 'timestamp'], name='api_securit_ip_addr_34b417_idx')],
            },
        ),
    ]
